default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: etherbeam_dev

test:
  <<: *default
  database: etherbeam_test

production:
  <<: *default
  database: etherbeam
